"""
Schemas Package
Export all Pydantic schemas
"""
from app.schemas.user import (
    UserBase,
    UserCreate,
    UserUpdate,
    UserResponse,
    UserInDB,
    PasswordChange,
)
from app.schemas.auth import (
    LoginRequest,
    TokenResponse,
    RefreshTokenRequest,
    PasswordResetRequest,
    PasswordResetConfirm,
)
from app.schemas.syllabus import (
    ExamTypeCreate,
    ExamTypeUpdate,
    ExamTypeResponse,
    ExamTypeWithStages,
    ExamStageCreate,
    ExamStageUpdate,
    ExamStageResponse,
    PaperCreate,
    PaperUpdate,
    PaperResponse,
    SubjectCreate,
    SubjectUpdate,
    SubjectResponse,
    TopicCreate,
    TopicUpdate,
    TopicResponse,
    TopicWithChildren,
)
from app.schemas.content import (
    ContentCreate,
    ContentUpdate,
    ContentResponse,
    ContentDetailResponse,
    ContentListResponse,
    ContentFilterParams,
    ContentTagCreate,
    ContentTagUpdate,
    ContentTagResponse,
    ContentTypeEnum,
    LanguageEnum,
    DifficultyLevelEnum,
    ContentStatusEnum,
)

__all__ = [
    # User
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "UserInDB",
    "PasswordChange",
    # Auth
    "LoginRequest",
    "TokenResponse",
    "RefreshTokenRequest",
    "PasswordResetRequest",
    "PasswordResetConfirm",
    # Syllabus
    "ExamTypeCreate",
    "ExamTypeUpdate",
    "ExamTypeResponse",
    "ExamTypeWithStages",
    "ExamStageCreate",
    "ExamStageUpdate",
    "ExamStageResponse",
    "PaperCreate",
    "PaperUpdate",
    "PaperResponse",
    "SubjectCreate",
    "SubjectUpdate",
    "SubjectResponse",
    "TopicCreate",
    "TopicUpdate",
    "TopicResponse",
    "TopicWithChildren",
    # Content
    "ContentCreate",
    "ContentUpdate",
    "ContentResponse",
    "ContentDetailResponse",
    "ContentListResponse",
    "ContentFilterParams",
    "ContentTagCreate",
    "ContentTagUpdate",
    "ContentTagResponse",
    "ContentTypeEnum",
    "LanguageEnum",
    "DifficultyLevelEnum",
    "ContentStatusEnum",
]
